### ISSUE TITLE
MVP Create Encounter Page

### ISSUE THREAD

**Issue by noahjade** [se701team3/Forgettable#44]
## Description
The create encounter page allows users to enter the information that will be stored as an "encounter". Below is the wireframe for the current layout design:

![image](https://user-images.githubusercontent.com/28725774/156979253-5c0f2865-b27c-42ef-a87a-d90c342b4007.png)

Note: for MVP, "insert image/video" is out of scope. The "delete" button is also out of scope for MVP, as we aren't introducing editing encounters yet.

## Acceptance Criteria

- [ ] Users should be able to add all relevant encounter fields
- [ ] When the save button is clicked, a call is made to the API and the new encounter is saved.
- [ ] When the save or the cancel button are clicked, the user is redirected back to the Person page for the associated person.
- [ ] UI should match the latest UI design

## Implementation details
- Check for latest UI design once its available.
- The side profile should be abstracted as a component if it doesn't already exist, so that it can be used on the Person details + encounters page as well.

## Testing notes
- Test that the calls are made to the API with appropriate information when save button is clicked (mock the call function)
- Test no calls to the API are made when cancel button clicked.

## Linked issues
#20 

## Reviewer
@cdra334

**Comment by cdra334** [comment]
LGTM. The new design doesn't use the side profile anymore I think so we don't have to worry about that part.
